name: CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: yarn install --silent --offline --frozen-lockfile
      - name: Run Code Linter
        run: yarn lint-code
      - name: Run Unit Tests
        run: yarn test
      - name: Publish to Storybook
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitZeroOnChanges: true
          exitOnceUploaded: true
      - name: Deploy to Vercel
        id: deploy
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      - name: Run End-to-End Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome e2e/tests --concurrency 2"
        env:
          TEST_URL: ${{ steps.deploy.outputs.preview-url }}
