name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --silent --frozen-lockfile
      - name: Lint
        run: yarn lint:code
      - name: Test
        run: yarn test
      - name: Storybook
        run: yarn build:storybook
      - name: Build
        run: yarn build
