name: End to End Tests

on: [deployment_status]

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Load Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --silent --frozen-lockfile
      - name: Run E2E Tests
        # TODO:
        run: yarn e2e
        env:
          TEST_URL: ${{ github.event.deployment_status.target_url }}
