name: End to End Tests

on: [deployment_status]

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Run E2E Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome e2e/tests --concurrency 2"
        env:
          TEST_URL: ${{ github.event.deployment_status.target_url }}
